<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.8" tiledversion="1.8.4" name="chapter99_00_tileset" tilewidth="8" tileheight="8" tilecount="4096" columns="64">
 <image source="../tsx/chapter99_00_tileset.png" width="512" height="512"/>
 <tile id="16" type="wall"/>
 <tile id="17" type="wall"/>
 <tile id="18" type="wall"/>
 <tile id="19" type="wall"/>
 <tile id="20" type="wall"/>
 <tile id="21" type="wall"/>
 <tile id="22" type="wall"/>
 <tile id="80" type="wall"/>
 <tile id="81" type="wall"/>
 <tile id="82" type="wall"/>
 <tile id="83" type="wall"/>
 <tile id="84" type="wall"/>
 <tile id="85" type="wall"/>
 <tile id="86" type="wall"/>
 <tile id="144" type="wall"/>
 <tile id="145" type="wall"/>
 <tile id="146" type="wall"/>
 <tile id="147" type="wall"/>
 <tile id="148" type="wall"/>
 <tile id="149" type="wall"/>
 <tile id="150" type="wall"/>
 <tile id="208" type="wall"/>
 <tile id="209" type="wall"/>
 <tile id="210" type="wall"/>
 <tile id="211" type="wall"/>
 <tile id="212" type="wall"/>
 <tile id="213" type="wall"/>
 <tile id="214" type="wall"/>
 <tile id="215" type="wall"/>
 <tile id="216" type="wall"/>
 <tile id="217" type="wall"/>
 <tile id="272" type="wall"/>
 <tile id="273" type="wall"/>
 <tile id="274" type="wall"/>
 <tile id="275" type="wall"/>
 <tile id="276" type="wall"/>
 <tile id="277" type="wall"/>
 <tile id="278" type="wall"/>
 <tile id="279" type="wall"/>
 <tile id="280" type="wall"/>
 <tile id="281" type="wall"/>
 <tile id="336" type="wall"/>
 <tile id="337" type="wall"/>
 <tile id="338" type="wall"/>
 <tile id="341" type="wall"/>
 <tile id="342" type="wall"/>
 <tile id="343" type="wall"/>
</tileset>
